name: Release CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          # use the minimum py ver we support to generate the wheel
          python-version: 3.8

      - name: install build deps
        run: |
          python -m pip install -U pip
          python -m pip install -U hatch

      - name: build wheel package
        run: |
          hatch build -t wheel

      - name: calculate checksum
        run: |
          for WHL in dist/*.whl; \
            do \
              sha256sum ${WHL} | sed -E "s@(\w+)\s+.*@sha256:\1@" > \
                ${WHL}.checksum; \
            done

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.checksum
