name: Release CI

on:
  release:
    types: [published]

jobs:
  build-and-upload-artifacts:
    name: build release packages and push gh artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          # use the minimum py ver we support to generate the wheel
          python-version: 3.8

      - name: install build deps
        run: |
          python -m pip install -U --disable-pip-version-check pip
          python -m pip install -U hatch build twine

      - name: build packages
        run: |
          hatch build

      - name: calculate checksum
        run: |
          for PKG in dist/*; \
            do \
              sha256sum ${PKG} | sed -E "s@(\w+)\s+.*@sha256:\1@" > \
                ${PKG}.checksum; \
            done

      - name: upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-and-upload-artifacts
          path: dist/*
          if-no-files-found: error

  publish-pypi:
    name: publish to pypi
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: build-and-upload-artifacts
    permissions:
      id-token: write

    steps:
      - name: download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-and-upload-artifacts
          path: dist

      - run: rm dist/*.checksum

      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          skip-existing: true
